
events {
    worker_connections  1024;
    # worker_processes and worker_connections allows you to calculate maxclients value: 
    # max_clients = worker_processes * worker_connections
}

http {
    sendfile on;
	server_tokens off;
	
	server {
		listen 80 ;
    	listen [::]:80 ;
		server_name cadenhird.com ;
    	root /www/site;
    	index index.html index.htm index.nginx-debian.html ;
    	location / {
    		try_files $uri $uri/ =404 ;
    	}
	}
}
