events {
    worker_connections  1024;
    # worker_processes and worker_connections allows you to calculate maxclients value:
    # max_clients = worker_processes * worker_connections
}
    
http {  
    sendfile on;
        server_tokens off;

        server {
                server_name cadenhird.com ;
        root /www/site;
        index index.html index.htm index.nginx-debian.html ;
        location / {
                try_files $uri $uri/ =404 ;
        }
        
    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/cadenhird.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cadenhird.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

        
        server {
    if ($host = cadenhird.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


                listen 80 ; 
        listen [::]:80 ;
                server_name cadenhird.com ;
    return 404; # managed by Certbot


}}
